aplicacao.nome=Sistema de vendas (properties)

#Porta do tomcat
server.port=8080
#Prefixo da url (http://localhost:8080/vendas/***)
#server.servlet.contextPath=/vendas

#Configuracao de acesso postgres
postgres.datasource.url=jdbc:postgresql://localhost:5432/bootexpert
postgres.datasource.username=expert
postgres.datasource.password=expert
postgres.datasource.driverclassname=org.postgresql.Driver
postgres.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#nao sei para que serve a linha abaixo
spring.mvc.view.suffix=.html
#serve para inibir retorno ao cliente de stacktrace no json
server.error.include-stacktrace=never

#definir usuário/senha fixa
spring.security.user.name=admin
spring.security.user.password=123

# Mostrar/ocultar detalhes
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=false

# DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.exclude=logs/**

